### ISSUE TITLE
`tr` command not found on `macOs` builds

### ISSUE THREAD

**Issue by zegnus** [Malinskiy/action-android#3] opened 2019-10-31 16:44 UTC
When using the following workflow

```
name: Android CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
      with:
        depth: 1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install Android SDK
      uses: malinskiy/action-android/install-sdk@release/0.0.2
    - name: Instrumentation Tests
      uses: malinskiy/action-android/emulator-run-cmd@release/0.0.2      
      with:
        cmd: ./team-props/instrumentation.sh
        api: 21
        tag: google_apis
        abi: x86
```

then in the command line I can see the following error:
```
/system/bin/sh: tr: not found
Sleeping for 1s
/Users/runner/android-sdk/platform-tools/adb shell getprop sys.boot_completed | tr -d '
```

it times out at the end and the emulator is correctly booted:
```
Timeout waiting for emulator to boot. Exiting
booted=false
emulator started and booted
```

**Comment by Malinskiy** [comment] 2019-10-31 23:49
Hey @zegnus! Can you please provide a link to the workflow yaml and a log?
I suspect you're running this on some new builds for macOS-10.15 which I'll need to check

**Comment by Malinskiy** [comment] 2019-11-06 05:16
I tried to reproduce this issue without success: https://github.com/Malinskiy/action-android/runs/290375749
The build is executed with `macOS-10.14` and `macOS-latest`.
I'll reach out to GH support but for now I don't know how to help here unless you share your workflow repo

**Comment by zegnus** [comment] 2019-11-07 11:25
hi @Malinskiy I managed to reproduce it in one of my public projects:

Workflow: https://github.com/zegnus/lite-download-manager/blob/master/.github/workflows/android.yml
Build: https://github.com/zegnus/lite-download-manager/runs/292528186

```
/Users/runner/android-sdk/platform-tools/adb shell getprop sys.boot_completed | tr -d '
'
/system/bin/sh: tr: not found
Sleeping for 1s
```

**Comment by Malinskiy** [comment] 2019-11-07 23:29
[Linked issue](https://github.com/actions/virtual-environments/issues/81) for virtual environments

**Comment by zegnus** [comment] 2019-11-08 09:33
hi @Malinskiy, unfortunately, I still see the issue when I use `macOS-10.14`:

https://github.com/zegnus/lite-download-manager/runs/294087916

**Comment by Malinskiy** [comment] 2019-11-08 09:40
I'll rework the action not to use `tr`. This doesn't solve the real problem though which is builds are not immutable :(
I'll update this issue after I release a new version

**Comment by zegnus** [comment] 2019-11-08 09:45
> builds are not immutable
exactly, that's a serious concern

👍 let me know and I'll give it another go

**Comment by Malinskiy** [comment] 2019-11-08 10:17
@zegnus please try out version `0.0.3`

**Comment by zegnus** [comment] 2019-11-08 11:21
That issue doesn't appear, but I get this instead:

```
2019-11-08T11:15:08.5614010Z error: device offline
2019-11-08T11:15:08.5615950Z Sleeping for 1s
2019-11-08T11:15:09.5638750Z [command]/Users/runner/android-sdk/platform-tools/adb shell getprop sys.boot_completed
2019-11-08T11:15:09.6687890Z 
2019-11-08T11:15:09.6697890Z Sleeping for 1s
2019-11-08T11:15:10.1584280Z eglMakeCurrent failed in binding subwindow!
2019-11-08T11:15:10.3348730Z eglMakeCurrent failed in binding subwindow!
2019-11-08T11:15:10.5267300Z emulator: ### WARNING: /etc/localtime does not point to zoneinfo-compatible timezone name
2019-11-08T11:15:10.5270560Z 
2019-11-08T11:15:10.7163280Z [command]/Users/runner/android-sdk/platform-tools/adb shell getprop sys.boot_completed
2019-11-08T11:15:10.7400660Z 
2019-11-08T11:15:10.7430940Z Sleeping for 1s
2019-11-08T11:15:10.9500560Z eglMakeCurrent failed in binding subwindow!
2019-11-08T11:15:10.9578780Z eglMakeCurrent failed in binding subwindow!
2019-11-08T11:15:10.9768800Z eglMakeCurrent failed in binding subwindow!
2019-11-08T11:15:11.0039470Z eglMakeCurrent failed in binding subwindow!
2019-11-08T11:15:11.0868200Z eglMakeCurrent failed in binding subwindow!
2019-11-08T11:15:11.1717500Z eglMakeCurrent failed in binding subwindow!
2019-11-08T11:15:11.2711350Z eglMakeCurrent failed in binding subwindow!
2019-11-08T11:15:11.3524720Z eglMakeCurrent failed in binding subwindow!
2019-11-08T11:15:11.4393040Z eglMakeCurrent failed in binding subwindow!
2019-11-08T11:15:11.5200120Z eglMakeCurrent failed in binding subwindow!
2019-11-08T11:15:11.6020950Z eglMakeCurrent failed in binding subwindow!
2019-11-08T11:15:11.6863700Z eglMakeCurrent failed in binding subwindow!
2019-11-08T11:15:11.7885570Z eglMakeCurrent failed in binding subwindow!
2019-11-08T11:15:11.7895990Z [command]/Users/runner/android-sdk/platform-tools/adb shell getprop sys.boot_completed
2019-11-08T11:15:11.8073300Z 
2019-11-08T11:15:11.8085190Z Sleeping for 1s
2019-11-08T11:15:11.8709170Z eglMakeCurrent failed in binding subwindow!
2019-11-08T11:15:11.9537280Z eglMakeCurrent failed in binding subwindow!
2019-11-08T11:15:12.0383660Z eglMakeCurrent failed in binding subwindow!
2019-11-08T11:15:12.1193990Z eglMakeCurrent failed in binding subwindow!
2019-11-08T11:15:12.2196100Z eglMakeCurrent failed in binding subwindow!
2019-11-08T11:15:12.3074300Z eglMakeCurrent failed in binding subwindow!
2019-11-08T11:15:12.3867050Z eglMakeCurrent failed in binding subwindow!
2019-11-08T11:15:12.4932190Z eglMakeCurrent failed in binding subwindow!
2019-11-08T11:15:12.5899810Z eglMakeCurrent failed in binding subwindow!
2019-11-08T11:15:12.6600280Z eglMakeCurrent failed in binding subwindow!
2019-11-08T11:15:12.7628830Z eglMakeCurrent failed in binding subwindow!
2019-11-08T11:15:12.8169490Z [command]/Users/runner/android-sdk/platform-tools/adb shell getprop sys.boot_completed
```

Does that look correct?
https://github.com/zegnus/lite-download-manager/runs/294221533

**Comment by Malinskiy** [comment] 2019-11-08 12:17
Nice. The repeating log message seems to be an issue with the new android emulator build. I'm not testing any UI on the action at the moment. Is there any indication that something is wrong on your tests side? I see the build passed using the emulator

**Comment by zegnus** [comment] 2019-11-15 17:34
Actually there are no tests, the command is just an empty gradle task, I was wondering if the repeating messages were something expected or now, that could have an impact on the overall speed of the task.

**Comment by Malinskiy** [comment] 2019-11-21 02:45
Since the original issue is now resolved I'm gonna close this. Feel free to reopen if the issue persists

**Closed by Malinskiy** 2019-11-21 02:45 UTC
